{
 "title": "IoT Device Dashboard",
 "tags": [ "DATASOURCE_UID" ],
 "time": { "from": "now-20m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "deviceid",
    "query": "select distinct deviceid from \"IOT_TELEMETRY_DATABASE\".\"device-telemetry\""
   }
  ]
 },
 "panels": [
  {
   "title": "Battery Performance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "\"IOT_TELEMETRY_DATABASE\"",
     "measure": "telemetry",
     "rawQuery": "SELECT deviceid as Device, \n  round(avg(battery_level),2) as Battery, \n  round(avg(fuel_level),2) as Fuel,\n  max(time) as time\nFROM \"IOT_TELEMETRY_DATABASE\".\"device-telemetry\" \nWHERE time between ago(15d) and now() \ngroup by deviceid\nORDER BY time DESC \nLIMIT 100 ",
     "table": "\"device-telemetry\""
    }
   ]
  },
  {
   "title": "Voltage (Battery)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"IOT_TELEMETRY_DATABASE\"",
     "measure": "telemetry",
     "rawQuery": "select battery_level as \"Voltage (Battery)\" from \"IOT_TELEMETRY_DATABASE\".\"device-telemetry\"",
     "table": "\"device-telemetry\""
    }
   ]
  },
  {
   "title": "Fuel Level",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"IOT_TELEMETRY_DATABASE\"",
     "measure": "telemetry",
     "rawQuery": "select fuel_level as \"Fuel Level\" from \"IOT_TELEMETRY_DATABASE\".\"device-telemetry\"",
     "table": "\"device-telemetry\""
    }
   ]
  },
  {
   "title": "Device Location",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "\"IOT_TELEMETRY_DATABASE\"",
     "measure": "telemetry",
     "rawQuery": "SELECT *, latitude as lat, longitude as lng \nFROM \"IOT_TELEMETRY_DATABASE\".\"device-telemetry\" \nWHERE time between ago(50d) and now() \nand deviceid = '$deviceid'\nORDER BY time \nDESC LIMIT 100",
     "table": "\"device-telemetry\""
    }
   ]
  },
  {
   "title": "Battery Voltage for $deviceid",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "\"IOT_TELEMETRY_DATABASE\"",
     "measure": "telemetry",
     "rawQuery": "SELECT battery_level as \"Voltage(Battery)\", time \nFROM \"IOT_TELEMETRY_DATABASE\".\"device-telemetry\" \nWHERE time between ago(60d) and now() \nand deviceid = '$deviceid'\nORDER BY time",
     "table": "\"device-telemetry\""
    }
   ]
  }
 ]
}